<html>
<head>
<base href="<?= $mvcHref ?>" />

<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"></script>
<script src='js/gb.js?v=3'        type='text/javascript'></script>
<script src='js/dmmaps.js'        type='text/javascript'></script>

<meta http-equiv='Content-Type'        content='text/html; charset=ISO-8859-1'>
<meta http-equiv='Content-Script-Type' content='text/javascript'>
<meta http-equiv='Content-Style-Type'  content='text/css'>
<meta http-equiv='Content-Language'    content='fr'>

<style>
 select                   {background:#eee; border:1px solid #999; padding:0px; background:url(img/inputbg.gif) repeat-x left top #d8d8d8;
}input.text               {background:#eee; border:1px solid #999; padding:1px; background:url(img/inputbg.gif) repeat-x left top #d8d8d8;
}textarea                 {background:#eee; border:1px solid #999; padding:1px; background:url(img/inputbg.gif) repeat-x left top #d8d8d8;
}input.password           {background:#eee; border:1px solid #999; padding:1px; background:url(img/inputbg.gif) repeat-x left top #d8d8d8;
}input.submit             {border:1px outset #999; padding:1px 20px; font-size:80%; font-weight:bold; cursor:pointer;
                           background:url(img/submitbg.gif) repeat-x left 20% #eee; color:#444;
}input:hover.submit       {border:1px inset #999;
                           background:url(img/submitbg.gif) repeat-x left 0% #fff;
}input:active.submit      {color:#000; padding:2px 19px 0px 21px; border:1px inset #999;
}.GBFORM                  {
}.GBFORM .OK              {padding:2px; margin:0px;
}.GBFORM .NOK             {border:2px solid #f00; padding:0px; margin:0px;
}.GBFORM .NOK .ERROR      {color:#f00;
}.GBFORM .PRE             {
}.GBFORM .POST            {font-style:italic; font-size:90%;
}.GBFORM_SPAN_OK          {display:inline; padding:2px; margin:0px;
}.GBFORM_SPAN_NOK         {display:inline; border:2px solid #f00; padding:0px; margin:0px;
}.GBFORM_SPAN_ERROR       {display:inline; color:#f00;
}

.inputcomment {
    margin:10px 0;
}
.inputcomment2 {
    width: 400px;
}

body {
    margin:0;
}
p, blockquote, ul, h1, h2, h3, h4, h5, h6 {
    margin: 0 0 5px 0;
}
ul {
    padding-left: 1.7em;
}
.main {
    width:1100px;    
}
.mainmap {
    float:left;
}
.rightpane {
    float:left;
    margin-left:10px;
    width:510px;
}
.map {
    border-collapse: collapse;
    border: none;
}
.map td,.case {
    margin: 0;
    padding: 0;
    width: 16px;
    height: 16px;
    text-align: center;
    color: white;
    font-size: smaller;
}
.map td img, #map td a {
    border: none;
}

img {
    border:0;
}
.authtarget{
    border:1px solid #000;
    margin:5px;
    padding:3px;
    background:#eee;
    float:left;
}
#hover-boxes div {
    border: 1px solid black;
    background: yellow;
    color: black;
    padding: 0.5em;
    position: absolute;
    display: none;
}
.clear{
    clear:both;
}
span.dmzone {
    border-bottom:1px dashed #555;
    display:inline-block;
}
</style>

<script type="text/javascript">
var currenthoverboxid = null;
var tileIds = [<?php echo implode(",", $tileIds); ?>];
var tileCount = <?php echo $tileCount; ?>;
var tilePrefix = '<?php echo $tilePrefix; ?>';
var tilePostfix = '<?php echo $tilePostfix; ?>';
var mapId = <?php echo $mapId; ?>;
var mapWidth = <?php echo $mapWidth; ?>;
var mapHeight = <?php echo $mapHeight; ?>;
var dungeonname = '<?php echo $dungeonName; ?>';
var level = '<?php echo $level; ?>';
var urllevelup = '<?php echo $urllevelup; ?>';
var urlleveldown = '<?php echo $urlleveldown; ?>';
</script>
