<!DOCTYPE html>
<html>
<head>
<base href="<?= $mvcHref ?>" />

<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js?key=ABQIAAAAnw9mTTFYya4bgEP1kvGNdBStAL7VVoZHM8UKknWFNjEBwFRjyhRaXzXZIdVtNeLyPYSwH3e3JtiTTw"></script>
<script src='js/dmmaps.js'        type='text/javascript'></script>
<link href="css/dmmaps.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type"        content="text/html; charset=UTF-8" />
<meta http-equiv='Content-Script-Type' content='text/javascript'>
<meta http-equiv='Content-Style-Type'  content='text/css'>
<meta http-equiv='Content-Language'    content='fr'>

<script type="text/javascript">
var currenthoverboxid = null;
var tileIds = [<?php echo implode(",", $tileIds); ?>];
var tileCount = <?php echo $tileCount; ?>;
var tilePrefix = '<?php echo $tilePrefix; ?>';
var tilePostfix = '<?php echo $tilePostfix; ?>';
var mapId = <?php echo $mapId; ?>;
var mapWidth = <?php echo $mapWidth; ?>;
var mapHeight = <?php echo $mapHeight; ?>;
var dungeonname = '<?php echo $dungeonName; ?>';
var level = '<?php echo $level; ?>';
var urllevelup = '<?php echo $urllevelup; ?>';
var urlleveldown = '<?php echo $urlleveldown; ?>';
</script>
