<?php
// vue appelée par edit.phtml dans id=authtargetid

// parameters:
/* @var $form     Gb_Form */
/* @var $urlLogin string */
/* @var $message  string */

$form
    ->setElementParam("login",    "preInput",  "Login :")
    ->setElementParam("login",    "postInput", "<br />")
    ->setElementParam("password", "preInput",  "Password :")
;
?>

<script type='text/javascript'>
<?= $form->getJavascript() ?>
</script>

<?= $form->getHtml() ?>

<? if (strlen($message)): ?>
    <div style="border:1px solid #f00;"><?= $message ?></div>
<? endif; ?>
<?= ajaxSubmit($urlLogin, "'authtargetid'", "submit", "{GBFORM_login:\$F('GBFORM_login'), GBFORM_password: \$F('GBFORM_password'), GBFORMPOST: \$F('GBFORMPOST')}") ?>

