<?php
// vue appelée par edit.phtml dans id=authtargetid

// parameters:
/* @var $form     Gb_Form */
/* @var $urlLogin string */
/* @var $message  string */

$form->getElem("login")->preInput("Login :");
$form->getElem("login")->postInput("<br />");
$form->getElem("password")->preInput("Password :");
?>

<script type='text/javascript'>
<?= $form->renderJavascript() ?>
</script>

<div class="GBFORM">
    <?= $form->renderHtml() ?>
</div>

<? if (strlen($message)): ?>
    <div style="border:1px solid #f00;"><?= $message ?></div>
<? endif; ?>
<?= ajaxSubmit($urlLogin, "'authtargetid'", "submit", "{".$form->getAjaxArgs()."}") ?>

