<?php
// parameters:

// $tileSize= array(width, height);
// $tileCount = nn; // number of 'different' tiles
// $tilePrefix = "tileimages/";
// $tilePostfix = ".gif";
// $mapId = "name of the map";
// $tileIds = array(tileIds);
// $mapWidth  =
// $mapHeight =
// $aNotes
// $urlswitch
// $urllevelup
// $urlleveldown
// $mvcHref

$mvc=Gb_Mvc::singleton();

include("controllers/shared/header.phtml");

?>

<title><?php echo "$mapId View" ?></title>
</head>
<body>

<?php
$cellPopups = array();
foreach( $aNotes as $annot ) {
    list($x,$y) = $annot[0];
    $cellId = $mapWidth*$y+$x;
    $cellPopups[$cellId] = "hover-box-$cellId";
    echo "<div class=\"hover-box\" id=\"hover-box-$cellId\">\n";
    echo str_replace("\n","<br />",htmlspecialchars($annot[1]));
    echo "</div>\n";
}

?>

<div class='main'>
    <div class='mainmap'>
        <table class="map">
        <caption>
        <? if ($urllevelup): ?>
        <a href='<?= $urllevelup ?>'><img src='tileimages/4.gif' title='up' /></a>
        <? else: ?>
        <img src='tileimages/2.gif' />
        <? endif; ?>
        Map of <?= $mapId ?>
        <? if ($urlleveldown): ?>
        <a href='<?= $urlleveldown ?>'><img src='tileimages/3.gif' title='down' /></a>
        <? else: ?>
        <img src='tileimages/2.gif' />
        <? endif; ?>
        </caption>
        <?php
        
        echo "<tr>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        for ($x=0; $x<$mapWidth; $x++)
        {
          $dig="";
          if (($x%10)==0)$dig=$x/10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
        }
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        for ($x=0; $x<$mapWidth; $x++)
        {
          $dig=$x%10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
        }
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "</tr>\n";
        
        for( $y=0; $y<$mapHeight; ++$y )
        {
          echo "<tr>\n";
          $dig="";
          if (($y%10)==0)$dig=$y/10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
          $dig=$y%10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
          for( $x=0; $x<$mapWidth; ++$x )
          {
            $cellId = $x+$y*$mapWidth;
            $tileId = $tileIds[$cellId];
            echo "\t<td id=\"cell-$cellId\"";
            if( isset($cellPopups[$cellId]) )
            {
                $popupId = $cellPopups[$cellId];
                echo " onmouseover=\"hoverPopup(event,'$popupId')\"";
                echo " onmouseout=\"hoverUnpop(event,'$popupId')\"";
                $tileId += 100;
            };
            if ($tileId==3) {
                echo " onclick=\"location.replace('$urlleveldown')\" style='cursor:pointer'";
            } elseif ($tileId==4) {
                echo " onclick=\"location.replace('$urllevelup')\" style='cursor:pointer'";
            }
            echo " background=\"{$tilePrefix}{$tileId}{$tilePostfix}\" ";
            echo "/>\n";
          }
          $dig="";
          if (($y%10)==0)$dig=$y/10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
          $dig=$y%10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
          echo "</tr>\n";
        }
        
        echo "<tr>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        for ($x=0; $x<$mapWidth; $x++)
        {
          $dig="";
          if (($x%10)==0)$dig=$x/10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
        }
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        for ($x=0; $x<$mapWidth; $x++)
        {
          $dig=$x%10;
          echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
        }
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "\t<td background=\"tileimages/0.gif\"></td>\n";
        echo "</tr>\n";
        
        
        
        
        ?>
        </table>
    </div>
    
    <div class="rightpane">
        <div style='text-align:right;'><a href='<?= $urlswitch ?>'>switch to edit mode</a></div>
    <?= $comments ?>
    </div>
    
    <div class='clear'></div>
</div>
</body>
</html>
