<?php
// parameters:

// $tileSize= array(width, height);
// $tileCount = nn; // number of 'different' tiles
// $tilePrefix = "tileimages/";
// $tilePostfix = ".gif";
// $mapId = id of the map;
// $tileIds = array(tileIds);
// $mapWidth  =
// $mapHeight =
// $aNotes
// $urlversion
// $urleditnotes
// $urlswitch
// $urllevelup
// $urlleveldown
// $mvcHref
// $userName
// $userDatemodif
// $userComment

$mvc=Gb_Mvc::singleton();

include("controllers/shared/header.phtml");

?>

<title><?php echo "$mapName View" ?></title>
</head>
<body>

<div id="hover-boxes">
    <?php
    $cellPopups = array();
    foreach( $aNotes as $annot ) {
        list($x,$y) = $annot[0];
        $cellId = $mapWidth*$y+$x;
        $cellPopups[$cellId] = "hover-box-$cellId";
        echo "<div id=\"hover-box-$cellId\">";
        echo str_replace("\n","<br />",htmlspecialchars($annot[1]));
        echo "</div>\n";
    }
    ?>
</div>

<div class='main'>
    <div class='mainmap'>
        <table class="map">
            <caption>
                <? if ($urllevelup): ?>
                    <a href='<?= $urllevelup ?>'><img src='tileimages/4.gif' width='16' height='16' title='up' /></a>
                <? else: ?>
                    <img src='tileimages/2.gif' />
                <? endif; ?>
                Map of <?= $mapName ?>
                <? if ($urlleveldown): ?>
                    <a href='<?= $urlleveldown ?>'><img src='tileimages/3.gif' width='16' height='16' title='down' /></a>
                <? else: ?>
                    <img src='tileimages/2.gif' />
                <? endif; ?>
            </caption>
            <tbody>
                <!-- Dynamically filled with javascript -->
            </tbody>
        </table>
    </div>
    
    <div class="rightpane">
        <div style='text-align:right;'><a href='<?= $urlswitch ?>'>switch to edit mode</a></div>
        <?= $comments ?>
        <div style='text-align:right;'><a href='<?= $urleditnotes ?>' target='_blank'>edit level notes</a></div>
        
        <div id='leveloverview'>
            This level hosts the
            <span class='dmzone' dmzone='[[[ 0, 9],[ 8,25]]]'>
                Wine Cellar
            </span>
            and the
            <span class='dmzone' dmzone='[ [[21,25]], [[20,26],[21,26]], [[20,27],[24,31]] ]' >
                lonely rat realm
            </span>
            .
        </div>
    </div><!-- .rightpane -->
    
    <div class='clear'></div>
    
    <div class='versions'>
        Versions:
        <select id='versionsid' onchange="location.replace($F('versionsid'));">
            <? foreach ($aVersions as $version): ?>
                <?
                $id=$version["id"];
                $vname=$version["user_name"].": ".htmlentities($version["comment"])." (".$version["datemodif"].")";
                $url=str_replace("@@@mapid@@@", $id, $urlVersion);
                $selected=  ($id==$mapId)?'selected="selected"':'';
                 ?>
                <option value='<?= $url ?>' <?= $selected ?>><?= $vname ?></option>
            <? endforeach; ?>
        </select>
    </div>
</div><!-- .main  -->


<div id='overlaymap' style='position:absolute; opacity:.75; display:none;'>
    <table class='map'>
        <tbody>
            <!-- Dynamically filled with javascript -->
        </tbody>
    </table>
</div>


<script>
DmmapMap.init("view");
DmmapTips.init();
DmmapZones.init();
DmmapHandlers.init("view");
</script>

</body>
</html>
