<?php
// parameters:

// $tileSize= array(width, height);
// $tileCount = nn; // number of 'different' tiles
// $tilePrefix = "tileimages/";
// $tilePostfix = ".gif";
// $mapId = id of the map;
// $dungeonname
// $level
// $mapName = "name of the map";
// $tileIds = array(tileIds);
// $mapWidth  =
// $mapHeight =
/* @var $urlSave String */
/* @var $urlDelete String */
// $mvcHref
// $fShowDelete
// $userName
// $userDatemodif
// $userComment
// $urlBase
// $urlswitch

$mvc=Gb_Mvc::singleton();

include("controllers/shared/header.phtml");

?>

<script>
tileIds = [<?php echo implode(",", $tileIds); ?>];
mapId   = <?= $mapId ?>;
</script>

<title><?php echo "$mapName Edit" ?></title>
</head>
<body>


<div class='main'>
    <div class='mainmap'>
        <table class="map">
            <caption>
                <? if ($urllevelup): ?>
                    <a href='<?= $urllevelup ?>'><img src='tileimages/4.gif' title='up' /></a>
                <? else: ?>
                    <img src='tileimages/2.gif' />
                <? endif; ?>
                Map of <?= $mapName ?>
                <? if ($urlleveldown): ?>
                    <a href='<?= $urlleveldown ?>'><img src='tileimages/3.gif' title='down' /></a>
                <? else: ?>
                    <img src='tileimages/2.gif' />
                <? endif; ?>
            </caption>
            <tbody>
                <!-- Dynamically filled with javascript -->
            </tbody>
        </table>
    </div>


    <div class="rightpane">
        <div style='text-align:right;'><a href='<?= $urlswitch ?>'>switch to view mode</a></div>

        <table id="palette" class="map">
            <tbody>
                <!-- Dynamically filled with javascript -->
           </tbobdy>
       </table>

       <div class='inputcomment'>
           <b>This version:</b><br />
           <?= htmlentities($userName) ?>: <?= htmlentities($userComment) ?> (<?= $userDatemodif ?>)<br />
           <br />
           <b>New version comments:</b>
           <br /><input type='text' id='comment' class='inputcomment2' />
       </div>


       <div id='authtargetid' class='authtarget'>
           <?= $mvc->callController("auth");  ?>
       </div>

       <?= ajaxSubmit(
           $urlSave,
           "'savetargetid'",
           "Save",
           "{dungeonname:dungeonname, levelnumber:level, comment:\$F('comment'), tileIds:tileIds.join(',')}",
           array(
               "condition"  => "\$F(\"comment\").length>5",
               "else"=>"alert(\"Please fill the comment.\")")
           ) ?>

       <? if ($fShowDelete): ?>
           <br />
           <?= ajaxSubmit($urlDelete, "'savetargetid'", "Delete this version", "{mapid:mapId}", array("condition"  => "confirm(\"You're gonna delete the version shown juste above.\")")) ?>
       <? endif; ?>

       <div id='savetargetid' class='savetarget'>
       </div>

    </div><!-- .rightpane -->

    <div class='clear'></div>
</div><!-- .main -->


<script>
DmmapMap.init("edit");
DmmapEditor.init();
DmmapHandlers.init("edit");
</script>

</body>
</html>
