<?php
// parameters:

// $tileSize= array(width, height);
// $tileCount = nn; // number of 'different' tiles
// $tilePrefix = "tileimages/";
// $tilePostfix = ".gif";
// $mapId = "name of the map";
// $dungeonname
// $level
// $mapName = "name of the map";
// $tileIds = array(tileIds);
// $mapWidth  =
// $mapHeight =
/* @var $urlSave String */
/* @var $urlDelete String */
// $mvcHref
// $fShowDelete
// $userName
// $userDatemodif
// $userComment

$mvc=Gb_Mvc::singleton();

include("controllers/shared/header.phtml");

?>



<title><?php echo "$mapName Edit" ?></title>
</head>
<body>


<div class='mainmap'>
    <table class="map">
    
    <caption>
    <? if ($urllevelup): ?>
    <a href='<?= $urllevelup ?>'><img src='tileimages/4.gif' title='up' /></a>
    <? else: ?>
    <img src='tileimages/2.gif' />
    <? endif; ?>
    Map of <?= $mapName ?>
    <? if ($urlleveldown): ?>
    <a href='<?= $urlleveldown ?>'><img src='tileimages/3.gif' title='down' /></a>
    <? else: ?>
    <img src='tileimages/2.gif' />
    <? endif; ?>
    </caption>
    
    
    <?php
    
    echo "<tr>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    for ($x=0; $x<$mapWidth; $x++)
    {
      $dig="";
      if (($x%10)==0)$dig=$x/10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
    }
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "</tr>\n";
    echo "<tr>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    for ($x=0; $x<$mapWidth; $x++)
    {
      $dig=$x%10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
    }
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "</tr>\n";
    
    for( $y=0; $y<$mapHeight; ++$y )
    {
      echo "<tr>\n";
      $dig="";
      if (($y%10)==0)$dig=$y/10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
      $dig=$y%10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
      for( $x=0; $x<$mapWidth; ++$x )
      {
        $cellId = $x+$y*$mapWidth;
        $tileId = $tileIds[$cellId];
        echo "\t<td id=\"cell-$cellId\"";
        echo " background=\"{$tilePrefix}{$tileId}{$tilePostfix}\"";
        echo " onclick=\"cellClicked($cellId)\"";
        echo "/>\n";
      }
      $dig="";
      if (($y%10)==0)$dig=$y/10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
      $dig=$y%10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
      echo "</tr>\n";
    }
    
    echo "<tr>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    for ($x=0; $x<$mapWidth; $x++)
    {
      $dig="";
      if (($x%10)==0)$dig=$x/10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
    }
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "</tr>\n";
    echo "<tr>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    for ($x=0; $x<$mapWidth; $x++)
    {
      $dig=$x%10;
      echo "\t<td background=\"tileimages/0.gif\">$dig</td>\n";
    }
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "\t<td background=\"tileimages/0.gif\"></td>\n";
    echo "</tr>\n";
    
    ?>
    </table>
</div>


<div class="rightpane">

<div style='text-align:right;'><a href='<?= $urlswitch ?>'>switch to view mode</a></div>


<table class="map">
<tr>
  <td background="tileimages/1.gif" onclick="toolClicked(1)"/>
  <td background="tileimages/2.gif" onclick="toolClicked(2)"/>
  <td background="tileimages/3.gif" onclick="toolClicked(3)"/>
  <td background="tileimages/4.gif" onclick="toolClicked(4)"/>
  <td background="tileimages/5.gif" onclick="toolClicked(5)"/>
  <td background="tileimages/6.gif" onclick="toolClicked(6)"/>
  <td background="tileimages/7.gif" onclick="toolClicked(7)"/>
  <td background="tileimages/8.gif" onclick="toolClicked(8)"/>
  <td background="tileimages/9.gif" onclick="toolClicked(9)"/>
  <td background="tileimages/10.gif" onclick="toolClicked(10)"/>
  <td background="tileimages/11.gif" onclick="toolClicked(11)"/>
  <td background="tileimages/12.gif" onclick="toolClicked(12)"/>
</tr>
</table>

<div class='inputcomment'>
    <b>This version:</b><br />
    <?= htmlentities($userName) ?>: <?= htmlentities($userComment) ?> (<?= $userDatemodif ?>)<br />
    <br />
    <b>New version comments:</b>
    <br /><input type='text' id='comment' class='inputcomment2' />
</div>


<div id='authtargetid' class='authtarget'>
    <?= $mvc->callController("auth");  ?>
</div>

<?= ajaxSubmit(
    $urlSave,
    "'savetargetid'",
    "Save",
    "{dungeonname:dungeonname, levelnumber:level, comment:\$F('comment'), tileIds:tileIds.join(',')}",
    array(
        "condition"  => "\$F(\"comment\").length>5",
        "else"=>"alert(\"Please fill the comment.\")")
    ) ?>

<? if ($fShowDelete): ?>
    <br />
    <?= ajaxSubmit($urlDelete, "'savetargetid'", "Delete this version", "{mapid:mapid}", array("condition"  => "confirm(\"You're gonna delete the version shown juste above.\")")) ?>
<? endif; ?>

<div id='savetargetid' class='savetarget'>
</div>

</div>

<div class='clear'></div>

</body>
</html>